- name: Our pre-setup
  hosts: k3s_cluster
  tasks:
  - name: Hello world
    ansible.builtin.copy:
      dest: /tmp/debug.txt
      content: |
        Environment Variables ("environment"):
        --------------------------------
        {{ environment | to_nice_json }}

        GROUP NAMES Variables ("group_names"):
        --------------------------------
        {{ group_names | to_nice_json }}

        GROUPS Variables ("groups"):
        --------------------------------
        {{ groups | to_nice_json }}

        HOST Variables ("hostvars"):
        --------------------------------
        {{ hostvars[inventory_hostname] | to_nice_json }}
- ansible.builtin.import_playbook: k3s.orchestration.site
